/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Automobil;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.component.table.model.AutomobilTableModel;

/**
 *
 * @author Vojin
 */
public class FAutomobil extends javax.swing.JFrame {

    private final int automobilID;
    private final String mode;
    private AutomobilTableModel model;
    /**
     * Creates new form FAutomobil
     */
    

    public FAutomobil(int automobilID) {
        initComponents();
        this.automobilID = automobilID;
        mode = "new";
        popuniFormu();
        setLocationRelativeTo(null);
        
    }
    
    public FAutomobil(Automobil a) {
        initComponents();
        this.automobilID = a.getAutomobilId();
        mode = "edit";
        popuniFormu(a);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtAutomobilID = new javax.swing.JTextField();
        jtxtRegistarskiBroj = new javax.swing.JTextField();
        jtxtMarka = new javax.swing.JTextField();
        jtxtModel = new javax.swing.JTextField();
        jtxtGodinaProizvodnje = new javax.swing.JTextField();
        jtxtBrojVrata = new javax.swing.JTextField();
        jcmbGorivo = new javax.swing.JComboBox<>();
        jtxtCenaNaDan = new javax.swing.JTextField();
        jcbDa = new javax.swing.JCheckBox();
        jcbNe = new javax.swing.JCheckBox();
        jbtnSacuvajAutomobil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Automobil");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Automobil"));

        jLabel1.setText("AutomobilID:");

        jLabel2.setText("RegistarskiBroj:");

        jLabel3.setText("Marka:");

        jLabel4.setText("Model:");

        jLabel5.setText("GodinaProizvodnje:");

        jLabel6.setText("BrojVrata:");

        jLabel7.setText("Gorivo:");

        jLabel8.setText("CenaNaDan:");

        jLabel9.setText("Raspoloziv:");

        jtxtAutomobilID.setEnabled(false);

        jcmbGorivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dizel", "Benzin", "Gas", "Benzin+Gas" }));

        jcbDa.setSelected(true);
        jcbDa.setText("Da");
        jcbDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDaActionPerformed(evt);
            }
        });

        jcbNe.setText("Ne");
        jcbNe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNeActionPerformed(evt);
            }
        });

        jbtnSacuvajAutomobil.setText("Sacuvaj automobil");
        jbtnSacuvajAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajAutomobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCenaNaDan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtGodinaProizvodnje, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtRegistarskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(jtxtAutomobilID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtBrojVrata, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addComponent(jtxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmbGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbDa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbNe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvajAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtAutomobilID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtRegistarskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jtxtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtGodinaProizvodnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jtxtBrojVrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcmbGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxtCenaNaDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jcbDa)
                            .addComponent(jcbNe))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbtnSacuvajAutomobil, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajAutomobilActionPerformed
        if(mode.equals("new")){
            try{
                Automobil automobil = validacija();
                String poruka = Controller.getInstance().sacuvajAutomobil(automobil);
                JOptionPane.showMessageDialog(this, poruka);
                jbtnSacuvajAutomobil.setEnabled(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            try{
                Automobil a = validacija();
                Controller.getInstance().promeniAutomobil(a);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio automobil.");
                jbtnSacuvajAutomobil.setEnabled(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_jbtnSacuvajAutomobilActionPerformed

    private void jcbDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDaActionPerformed
        if(jcbNe.isSelected())
            jcbNe.setSelected(false);
        jcbDa.setSelected(true);
    }//GEN-LAST:event_jcbDaActionPerformed

    private void jcbNeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNeActionPerformed
        if(jcbDa.isSelected())
            jcbDa.setSelected(false);
        jcbNe.setSelected(true);
    }//GEN-LAST:event_jcbNeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    private void popuniFormu() {
        
        jtxtAutomobilID.setText(automobilID + "");
    }

    private void popuniFormu(Automobil a) {
        jbtnSacuvajAutomobil.setEnabled(true);
        jtxtAutomobilID.setText(automobilID+ " ");
        
        jtxtRegistarskiBroj.setText(a.getRegistarskiBroj());
        jtxtMarka.setText(a.getMarka());
        jtxtModel.setText(a.getModel());
        jtxtGodinaProizvodnje.setText(String.valueOf(a.getGodinaProizvodnje()));
        jtxtBrojVrata.setText(String.valueOf(a.getBrojVrata()));
        jcmbGorivo.setSelectedItem(a.getGorivo());
        jtxtCenaNaDan.setText(String.valueOf(a.getCenaNaDan()));
        if(a.isRaspoloziv()){
            jcbDa.setSelected(true);
            jcbNe.setSelected(false);
        }else{
            jcbDa.setSelected(false);
            jcbNe.setSelected(true);
        }
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSacuvajAutomobil;
    private javax.swing.JCheckBox jcbDa;
    private javax.swing.JCheckBox jcbNe;
    private javax.swing.JComboBox<String> jcmbGorivo;
    private javax.swing.JTextField jtxtAutomobilID;
    private javax.swing.JTextField jtxtBrojVrata;
    private javax.swing.JTextField jtxtCenaNaDan;
    private javax.swing.JTextField jtxtGodinaProizvodnje;
    private javax.swing.JTextField jtxtMarka;
    private javax.swing.JTextField jtxtModel;
    private javax.swing.JTextField jtxtRegistarskiBroj;
    // End of variables declaration//GEN-END:variables

    private Automobil validacija() throws Exception {
        
        if(jtxtRegistarskiBroj.getText().isEmpty() || jtxtMarka.getText().isEmpty() || jtxtModel.getText().isEmpty() || 
                jtxtGodinaProizvodnje.getText().isEmpty() || jtxtBrojVrata.getText().isEmpty() || jtxtCenaNaDan.getText().isEmpty() || 
                (jcbDa.isSelected() && jcbNe.isSelected()) || (!jcbDa.isSelected() && !jcbNe.isSelected()))
            throw new Exception("Sva polja moraju biti popunjena.");
        
        if(!jtxtBrojVrata.getText().matches("[0-9]+") || !jtxtGodinaProizvodnje.getText().matches("[0-9]+") || !jtxtCenaNaDan.getText().matches("[0-9]+"))
            throw new Exception("Broj vrata,godina proizvodnje i cena na dan mogu sadrzati samo brojeve.");
        
        String registarskiBroj = jtxtRegistarskiBroj.getText();
        String marka = jtxtMarka.getText();
        String model = jtxtModel.getText();
        int godinaProizvodnje = Integer.parseInt(jtxtGodinaProizvodnje.getText());
        int brojVrata = Integer.parseInt(jtxtBrojVrata.getText());
        String gorivo  = (String) jcmbGorivo.getSelectedItem();
        int cenaNaDan = Integer.parseInt(jtxtCenaNaDan.getText());
        boolean raspoloziv = true;
        
        if(jcbNe.isSelected())
            raspoloziv = false;
        
        return new Automobil(automobilID, registarskiBroj, marka, model, godinaProizvodnje, brojVrata, gorivo, cenaNaDan, raspoloziv);
        
    }
}
