/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Banka;
import domain.Klijent;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Vojin
 */
public class FKlijent extends javax.swing.JFrame {

    private int sifra;
    List<Banka> banke;
    private final String mode;
    
    /**
     * Creates new form FKlijent
     */
    public FKlijent() {
        initComponents();
        mode = "new";
        try{
            banke = Controller.getInstance().vratiBanke();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        setLocationRelativeTo(null);
        popuniFormu();
    }
    
    public FKlijent(Klijent k){
        initComponents();
        
        try{
            banke = Controller.getInstance().vratiBanke();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        this.sifra = k.getKlijentID();
        mode = "edit";
        popuniFormu(k);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtKlijentID = new javax.swing.JTextField();
        jtxtJmbg = new javax.swing.JTextField();
        jtxtIme = new javax.swing.JTextField();
        jtxtPrezime = new javax.swing.JTextField();
        jtxtAdresa = new javax.swing.JTextField();
        jtxtBrojTelefona = new javax.swing.JTextField();
        jcmbBanka = new javax.swing.JComboBox();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Klijent");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Klijent"));

        jLabel1.setText("KlijentID:");

        jLabel2.setText("JMBG:");

        jLabel3.setText("Ime:");

        jLabel4.setText("Prezime:");

        jLabel5.setText("Adresa:");

        jLabel6.setText("Broj telefona:");

        jLabel7.setText("Banka:");

        jtxtKlijentID.setEnabled(false);

        jcmbBanka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcmbBanka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtJmbg)
                    .addComponent(jtxtIme)
                    .addComponent(jtxtAdresa)
                    .addComponent(jtxtPrezime)
                    .addComponent(jtxtBrojTelefona)
                    .addComponent(jtxtKlijentID))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtKlijentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPrezime)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbBanka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jbtnSacuvaj.setText("Sačuvaj klijenta");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnDodaj.setText("Dodaj još jednog klijenta");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jbtnDodaj))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        if(mode.equals("new")){
            try{
                Klijent klijent = validacija();
                String poruka = Controller.getInstance().sacuvajKlijenta(klijent);
                JOptionPane.showMessageDialog(this, poruka);
                jbtnDodaj.setEnabled(true);
                jbtnSacuvaj.setEnabled(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            try{
                Klijent k = validacija();
                Controller.getInstance().promeniKlijenta(k);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio klijenta.");
                jbtnSacuvaj.setEnabled(false);
                jbtnDodaj.setEnabled(true);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        resetujFormu();
        jbtnSacuvaj.setEnabled(true);
        jbtnDodaj.setEnabled(false);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcmbBanka;
    private javax.swing.JTextField jtxtAdresa;
    private javax.swing.JTextField jtxtBrojTelefona;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtJmbg;
    private javax.swing.JTextField jtxtKlijentID;
    private javax.swing.JTextField jtxtPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() {
        
        jbtnDodaj.setEnabled(false);
        
        try{
            int  klijentId= Controller.getInstance().kreirajKlijenta();
            sifra = klijentId;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            dispose();
        }
        
        jtxtKlijentID.setText(sifra + "");
        jcmbBanka.removeAllItems();
        
        for (Banka b : banke) {
            jcmbBanka.addItem(b);
        }
    }

    private void popuniFormu(Klijent k) {
        
        jbtnDodaj.setEnabled(false);
        jtxtKlijentID.setText(sifra+ "");
        
        jcmbBanka.removeAllItems();
        for (Banka b : banke) {
            jcmbBanka.addItem(b);
        }
        
        jtxtJmbg.setText(k.getJmbg());
        jtxtIme.setText(k.getIme());
        jtxtPrezime.setText(k.getPrezime());
        jtxtAdresa.setText(k.getAdresa());
        jtxtBrojTelefona.setText(k.getBrojTelefona());
        
    }

    private Klijent validacija() throws Exception {
        
        if(jtxtJmbg.getText().isEmpty() || jtxtIme.getText().isEmpty() || jtxtPrezime.getText().isEmpty() || 
                jtxtAdresa.getText().isEmpty() || jtxtBrojTelefona.getText().isEmpty())
            throw new Exception("Sva polja moraju biti popunjena.");
        
        String jmbg = jtxtJmbg.getText();
        
        if(jmbg.length() != 13 || !jmbg.matches("[0-9]+"))
            throw new Exception("JMBG mora imati tacno 13 cifara i ne sme sadrzati nista drugo sem cifara.");
        
        String ime = jtxtIme.getText();
        String prezime = jtxtPrezime.getText();
        String adresa = jtxtAdresa.getText();
        String brojTelefona = jtxtBrojTelefona.getText();
        
        if(!brojTelefona.matches("[0-9]+"))
            throw new Exception("Broj telefona sme sadrzati samo cifre.");
        
        Banka banka = (Banka) jcmbBanka.getSelectedItem();
        
        return new Klijent(sifra, jmbg, ime, prezime, adresa, brojTelefona, banka);
    }

    private void resetujFormu() {
        
        try{
            int klijentovid = Controller.getInstance().kreirajKlijenta();
            sifra = klijentovid;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            dispose();
        }
        jtxtKlijentID.setText(sifra + "");
        jtxtJmbg.setText("");
        jtxtIme.setText("");
        jtxtPrezime.setText("");
        jtxtAdresa.setText("");
        jtxtBrojTelefona.setText("");
    }
}
